### ISSUE TITLE
Entities gone after 3.10.3 update

### ISSUE THREAD

**Issue by JackTalisker** [custom-components/alexa_media_player#1296]
**Describe the bug**
Updated integration via HACS to 3.10.3. All my Alexa entities are suddenly unavailable.

Error fetching alexa_media data: Error communicating with API: 'NoneType' object has no attribute 'get'

**To Reproduce**
Just start HA and the integration

**System details**
 - Home-assistant (version):  Home Assistant Core 2021.5.3 : Manual installation using Python virtual environment.
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

 **Logs**
Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:212
Integration: Alexa Media Player (documentation, issues)
First occurred: 8:30:29 (1 occurrences)
Last logged: 8:30:29

Error fetching alexa_media data: Error communicating with API: 'NoneType' object has no attribute 'get'

**Additional context**
All my Alexa related entities are unavailable

**Comment by micium** [comment]
I had the same problem after updated to v 3.10.3.
I did a rollback to previous version and the problem is resolved.

**Comment by alandtse** [comment]
Thanks. Can you provide the full error logs?

@blm126 can you look for see if your changes may have had an impact?

**Comment by maverik80** [comment]
guys also for me the same problem, after updating to 3.10.3 all entities disappeared, returned to 3.10.2 all regular

**Comment by JackTalisker** [comment]
`
-------------------------------------------------------------------
alexa_media
Version: 3.10.3
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2021-05-15 09:11:27 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.25.1
2021-05-15 09:11:28 DEBUG (MainThread) [custom_components.alexa_media.helpers] c************e@y********m: Returning uuid {'uuid': 'xxxxxxxxxxxxxxxxxxxxxxxx', 'index': 0}
2021-05-15 09:11:28 DEBUG (MainThread) [alexapy.alexalogin] Login created for c************e@y********m - amazon.it
2021-05-15 09:11:28 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /home/homeassistant/.homeassistant/.storage/alexa_media.c************e@y********m.pickle
2021-05-15 09:11:28 DEBUG (MainThread) [alexapy.alexalogin] Trying to load cookie from file /home/homeassistant/.homeassistant/.storage/alexa_media.c************e@y********m.pickle
2021-05-15 09:11:35 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
2021-05-15 09:11:35 DEBUG (MainThread) [alexapy.alexalogin] Loaded 14 cookies
2021-05-15 09:11:35 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /home/homeassistant/.homeassistant/alexa_media.c************e@y********m.pickle
2021-05-15 09:11:35 DEBUG (MainThread) [alexapy.alexalogin] Using cookies to log in
2021-05-15 09:11:35 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.it
2021-05-15 09:11:39 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.it/auth/register) [200 OK]>
<CIMultiDictProxy('Server': 'Server', 'Date': 'Sat, 15 May 2021 07:11:38 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '5670', 'Connection': 'keep-alive', 'x-amz-rid': 'xxxxxxxxxxxxxxx', 'x-amzn-RequestId': 'xxxxxxxxxxxxxxxxxxxxx', 'X-Amz-Date': 'Sat, 15 May 2021 07:11:38 GMT', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent')>
 with 

[.........................]

2021-05-15 09:11:39 DEBUG (MainThread) [alexapy.alexalogin] Successfully registered Gherardo's 2nd Alexa Media Player device with Amazon
2021-05-15 09:11:39 DEBUG (MainThread) [alexapy.alexalogin] New access token received which expires at 2021-05-15 10:11:39.639235 in 0:59:59.999930
2021-05-15 09:11:41 DEBUG (MainThread) [alexapy.alexalogin] 5 cookies successfully exchanged for refresh token for domain .amazon.it
2021-05-15 09:11:41 DEBUG (MainThread) [alexapy.alexalogin] CSRF already exists; no need to discover
2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] GET: redirected from
https://alexa.amazon.com/api/bootstrap
2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] GET: 

[..........]

2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] GET: 

[................]

2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] Logged in as c************e@y********m to amazon.it with id: A2ARAIKOQBB085
2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] Domain amazon.it matches reported account domain: https://www.amazon.it
2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexalogin] Login confirmed for c************e@y********m - amazon.it; saving cookie to /home/homeassistant/.homeassistant/.storage/alexa_media.c************e@y********m.pickle
2021-05-15 09:11:45 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {'login_successful': True}
2021-05-15 09:11:45 DEBUG (MainThread) [custom_components.alexa_media] Setting up Alexa devices for c************e@y********m
2021-05-15 09:11:45 DEBUG (MainThread) [custom_components.alexa_media] c************e@y********m: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x6895e0a0>
2021-05-15 09:11:45 DEBUG (MainThread) [alexapy.alexawebsocket] Connecting to wss://dp-gw-na.amazon.it/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=-xxxxxxxxxxxx with {'User-Agent': 'AmazonWebView/Alexa Media Player/2.2.223830.0/iOS/11.4.1/iPhone', 'Accept': '*/*', 'Accept-Language': '*', 'DNT': '1', 'Upgrade-Insecure-Requests': '1', 'Referer': 'https://alexa.amazon.it/api/bootstrap', 'authority': 'www.amazon.it', 'Origin': 'https://alexa.amazon.it'}
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Initating Async Handshake.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: 0x37a3b607 0x0000009c {"protocolName":"A:H","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Handshake MSG.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000361 0xffcb3cc0 f 0x00000001 0xcabb79e7 0x000000b9 ACK 0x00000003 1.0 0x00000024 01e09e62-f504-476c-85c8-9c97c8da26ed 0x00000064 0x0000016978ff598c 0x000001796edde4d6 END FABE
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Received ACK MSG for Registration.
2021-05-15 09:11:46 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2021-05-15 09:11:47 DEBUG (MainThread) [custom_components.alexa_media] c************e@y********m: Websocket successfully connected
2021-05-15 09:11:47 DEBUG (MainThread) [custom_components.alexa_media] c************e@y********m: Creating coordinator
2021-05-15 09:11:47 DEBUG (MainThread) [custom_components.alexa_media] c************e@y********m: Refreshing coordinator
2021-05-15 09:11:47 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/bootstrap returned 200:OK:application/json
2021-05-15 09:11:47 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/phoenix returned 200:OK:application/json
2021-05-15 09:11:47 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: get_network_details response: {'locationDetails': {'locationDetails': 

[................]

'NO_AUTOMATIC_SELECTION_POSSIBLE', 'lastUpdated': '1605981335550'}}, 'space': False}}}}}}, 'version': '1.0', 'relations': []}
2021-05-15 09:11:47 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/devices-v2/device returned 200:OK:application/json
2021-05-15 09:11:47 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/dnd/device-status-list returned 200:OK:application/json
2021-05-15 09:11:48 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/device-preferences returned 200:OK:application/json
2021-05-15 09:11:48 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static GET: https://alexa.amazon.it/api/bluetooth?cached=false returned 200:OK:application/json
2021-05-15 09:11:48 DEBUG (MainThread) [custom_components.alexa_media] Alexa entities have been loaded. Prepared for discovery.
2021-05-15 09:11:49 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: static POST: https://alexa.amazon.it/api/phoenix/state returned 400:Bad Request:application/json
2021-05-15 09:11:49 DEBUG (MainThread) [alexapy.alexaapi] c************e@y********m: get_entity_state response: None
2021-05-15 09:11:49 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 'NoneType' object has no attribute 'get'
2021-05-15 09:11:49 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 2.030 seconds
2021-05-15 09:12:00 DEBUG (MainThread) [custom_components.alexa_media] Completing remaining startup tasks.

`

**Comment by mikesalz** [comment]
Same here...

**Comment by maverik80** [comment]
I tried several times to redo the whole integration from the beginning and the tenth time it worked, I don't know why all this

**Comment by javiges** [comment]
The same thing happens to me, I had to download the version

**Comment by serlinGi** [comment]
Same for me after this update

**Comment by blm126** [comment]
Can anyone confirm whether you have Alexa Guard enabled or disabled? Current theory is that this occurs when you have guard disabled.

**Comment by Camatobe** [comment]
It’s disabled in my country. So yes. Can confirm: Issue occurs when guard is disabled

**Comment by JackTalisker** [comment]
Alexa guard is not available in my country at the moment.

**Comment by micium** [comment]
Alexa guard is not available in Italy at the moment.

**Comment by blm126** [comment]
I believe that I have fixed this. However, I can't figure out how to get Amazon to disable Guard on my account so I had to fake that state in code for testing.

If this is currently broken for you, I would request that you try out my PR. That should be as simple as upgrading to 3.10.3 and then overwriting custom_components/alexa_media/alexa_entity.py with the contents of [that file on my branch](https://github.com/blm126/alexa_media_player/blob/MissingEntity/custom_components/alexa_media/alexa_entity.py).

**Comment by canna051** [comment]
Same here :-( 
I reloaded last snapshot

**Comment by JackTalisker** [comment]
1. Updated to 3.10.3 via hacs
2. Not restarted and stopped HA 
3. replaced alexa_entity.py with the new one
4. restarted HA
5. It works as expected now
