### ISSUE TITLE
New default tts missing or misunderstanding?

### ISSUE THREAD

**Issue by pedolsky** [custom-components/alexa_media_player#1764]
**Describe the bug**
I dont know if it's really a bug or if I simply misunderstood the release note.

After updating to v4.2.0 I've expected not to have to type `type: tts` anymore. But if I leave it out, the service won't work ('unknown error').

**To Reproduce**
Try to call the service without defining the notify type.

**Expected behavior**

expected not to have to type `type: tts` anymore

**Screenshots**

**System details**
 - Home-assistant (version): 2022.11.0b1
 - alexa_media  (version from `const.py` or HA startup): 4.2.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.4
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  yes

**Logs**

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:242 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 18:42:05 (1 occurrences) 
Last logged: 18:42:05

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 258, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 242, in async_send_message
    data_type = data.get("type", "tts")
AttributeError: 'NoneType' object has no attribute 'get'

**Additional context**

**Comment by alandtse** [comment]
@provinzio any thoughts? Looks like the default should have had a None check on data too.

**Comment by provinzio** [comment]
It looks like home assistant is passing a None entry for data when nothing is specified. 

Checking for None in the beginning of the function, directly after reading data from the message dict, should solve the problem. 

`data = data if data else {}`

**Comment by alandtse** [comment]
No rush, just whenever you want to submit a PR.
